name: C/C++ CI

on:
  push:
    branches: [ Nethunter-LOS ]
  pull_request:
    branches: [ Nethunter-LOS ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: ./build.sh

